version: 2

jobs:
  build:
    working_directory: ~/circle_2_tests
    docker:
      - image: circleci/ruby:latest
        environment:
          IGNORE_PATHS: ignored1
          TRIGGER_PATHS: trigger1
    steps:
      - checkout
      - run:
          command: bash .circleci/skip_paths.sh
      - run:
          command: |
            echo $IGNORE_PATHS
            echo $TRIGGER_PATHS
            echo $RUN_STEP
      - run:
          command: |
            echo $IGNORE_PATHS
            echo $TRIGGER_PATHS
            echo $RUN_STEP
          environment:
            IGNORE_PATHS: circleci
